language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10'
os:
    - linux
cache: pip
install:
  - pip install -r requirements.txt
script:
  - nosetests tests --with-coverage --cover-package=logmole
after_success:
  - coveralls